spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    password: wowlg147
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

